name = "SearchNetworks"
uuid = "17666995-d420-48ac-8d7c-8a155fef8e5d"
authors = ["Camilo De La Torre <camilo.de-la-torre@ut-capitole.fr> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
